### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by saharshleo** [ganadhish1999/SAGA#2]

**Comment by akshatshah21** [comment]
@saharshleo  Will you upload  the PDF Documentation?

**Comment by saharshleo** [comment]
https://drive.google.com/drive/folders/1RS5m2YWh2JR9mIOzwHoZCks08bSaLzKg
@akshatshah21

**Comment by akshatshah21** [comment]
#3 The documentation has been added and is now on master
